### ISSUE TITLE
82f5faa5f68215564ee9ae7dfd0d26bc6dd58325  Cannot build: ConfigError

### ISSUE THREAD

**Issue by cleong110** [LuanRT/BgUtils#6]
### Steps to reproduce

In Google Colab I tried to run `npm install` and got "Config Error".

https://colab.research.google.com/drive/10x_3XJIYKvjK9hxD3yMRmtSDuQXdnLZ_#scrollTo=09dUXTAr1D44

### Failure Logs

```shell
ConfigError: Config (unnamed): Key "rules": Key "constructor-super": structuredClone is not defined
    at rethrowConfigError (/content/BgUtils/node_modules/@eslint/config-array/dist/cjs/index.cjs:303:8)
    at /content/BgUtils/node_modules/@eslint/config-array/dist/cjs/index.cjs:1098:5
    at Array.reduce (<anonymous>)
    at FlatConfigArray.getConfigWithStatus (/content/BgUtils/node_modules/@eslint/config-array/dist/cjs/index.cjs:1091:43)
    at FlatConfigArray.getConfig (/content/BgUtils/node_modules/@eslint/config-array/dist/cjs/index.cjs:1120:15)
    at /content/BgUtils/node_modules/eslint/lib/eslint/eslint.js:960:40
    at Array.map (<anonymous>)
    at ESLint.lintFiles (/content/BgUtils/node_modules/eslint/lib/eslint/eslint.js:958:23)
    at async Object.execute (/content/BgUtils/node_modules/eslint/lib/cli.js:502:23)
    at async main (/content/BgUtils/node_modules/eslint/bin/eslint.js:153:22)
```

### Expected behavior

Not sure. I wanted to run the examples, instructions said to "build first", so I gave this a try. I don't know much about npm, javascript etc. I suppose I wanted to build it, then run the `node` example.

### Current behavior

Build doesn't work, possibly my fault? Or Colab's?

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment]
Looks like the linter failed. Try `npm run build:esm && npm run bundle:node`.
I don't use Colab's much so I can't say for sure why it won't compile there.
